title = "Introduction to Probability and Statistics"
baseURL = "https://www.stat20.org"
languageCode = "en-us"
theme = "hugo-apero"
author = "Andrew Bray"
copyright = ""
googleAnalytics = ""
disqusShortname = ""
metaDataFormat = "yaml"
footnoteReturnLinkContents = "&#8617;" # â†©
paginate = 50
preserveTaxonomyNames = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
enableEmoji = true

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark.renderer]
    unsafe = true  # Enable user to embed HTML snippets in Markdown content.
    hardwraps = false
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 2
    ordered = false
  [markup.highlight]
    # one of: https://xyproto.github.io/splash/docs/
    style = ""
    falseClasses = false
    
[params]
  description = "Welcome to the course. We're glad you're here."
  favicon = "/img/favicon.ico"
  logo = "/img/stat20-hex.png"
  mainSections = ["syllabus", "schedule", "labs", "problem sets"]
  navallcaps = true
  orgName = "Andrew Bray"
  #sharing_image = "/img/papillons.jpg"
  socialInFooter = true
  socialInHeader = true

  # use a built-in color theme
  # one of: forest / grayscale / peach / plum /
  #         poppy / sky / violet / water
  theme = ""

  # or, leave theme empty & make your own palette
  # see docs at https://hugo-apero.netlify.app/blog/color-themes/
  # the custom scss file must be in the assets/ folder
  # add the filename name here, without extension
  # to use hex colors instead of named tachyons colors, include "hex" in filename
  custom_theme = "garrick-hex"
  show_post_thumbnail = false

  # use an embedded font-family
  # serif options: Fraunces / EB Garamond / Bitter
  # sans-serif options: Commissioner / Atkinson Hyperlegible / Metropolis
  # if you import your own fonts, name them here too
  customtextFontFamily = ""
  customheadingFontFamily = ""
  # alternatively, leave empty and select basic font options: sans-serif or serif
  # for more http://tachyons.io/docs/typography/font-family/
  textFontFamily = "sans-serif"
  headingFontFamily = "avenir"

  [[params.social]]
      icon      = "comments" # icon name without the 'fa-'
      icon_pack = "far"
      url       = "https://edstem.org/us/courses/18678/discussion/"
  [[params.social]]
      icon      = "r-project" # icon name without the 'fa-'
      icon_pack = "fab"
      url       = "https://stat20.datahub.berkeley.edu/"
  [[params.social]]
      icon      = "chart-bar" # icon name without the 'fa-'
      icon_pack = "fas"
      url       = "https://www.gradescope.com/courses/356299"
  [[params.social]]
      icon      = "video" # icon name without the 'fa-'
      icon_pack = "fas"
      url       = "https://bcourses.berkeley.edu/courses/1513313/external_tools/78985"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[menu]
  [[menu.footer]]
    name = "Made with help"
    title = "Made with help"
    url = "/colophon/"
    weight = 1
  [[menu.header]]
    name = "Syllabus"
    title = "Syllabus"
    url = "/syllabus/"
    weight = 1
  [[menu.header]]
    name = "Schedule"
    title = "Schedule"
    url = "/schedule/"
    weight = 2
  [[menu.header]]
    name = "Labs"
    title = "Labs"
    url = "/lab/"
    weight = 3
  [[menu.header]]
    name = "Problem Sets"
    title = "Problem Sets"
    url = "/ps/"
    weight = 4

# see https://gohugo.io/about/hugo-and-gdpr/
[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    disable = false
    anonymizeIP = true
    respectDoNotTrack = true
  [privacy.instagram]
    disable = false
    simple = true
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = false
  [privacy.vimeo]
    disable = false
    enableDNT = true
    simple = true
  [privacy.youtube]
    disable = false
    privacyEnhanced = true